
#################################################################################################### 
# Function Name: fracWeights 
# Description: Generate the weights for fractional differencing.
# Inputs 
# [1] d
# [2] size
# Outputs:
# [1] weightValues 
#  
#  
fracWeights <- function(d,size) { 
  weightValues = c(1)
  for(k in 1:size){
    weightValues[k+1] <- -1*weightValues[k ]/k*(d-k+1) }
   return(weightValues) }
#####################################################################################################
 


#################################################################################################### 
# Function Name: fixedWindowFracDiff 
# Description: Calculate the weights to be used in fractional differencing; truncate the weights based on some threshold.
# Inputs 
# [1] d - the fractional differencing to be used.
# [2] threshold - numeric representing the threshold for truncating the weights generated by the function.
#     Defaults to 1e-5
# [3] size = The number of results to generate from the fracWeights function. Defaults to 10.
# Outputs:
# [1] fracDiffWeights - a list of weights to be used in fractional differencing. 
#  
#  
fixedWindowFracDiff <- function(d,threshold= 1-5,size =10 ){ 
  fracWeightsVals <- fracWeights(d,size)
  fracDiffWeights <- fracWeightsVals[abs(fracWeightsVals)> threshold ]
   return(fracDiffWeights) } 
#  
#####################################################################################################


#################################################################################################### 
# Function Name: genFracWeightedSeries 
# Description: Generates a fractionally differenced series based on data, as well as d, size, and threshold
# Inputs 
# [1] dataSeries
# [2] d
# [3] size
# Outputs:
# [1] fracDiffSeries 
#  
#  
genFracWeightedSeries <- function(dataSeries,d,threshold = 1e-5,size = 10) { 
   diffWeights <- fixedWindowFracDiff(d,threshold,size )
   weightedData <- lapply(1:(length(diffWeights)-1),FUN = function(x){ shift(dataSeries, x )*diffWeights[x+1]     }) %>% as.data.table
   summedWeighted <- apply(weightedData, MARGIN = 1, sum)
   fracDiffSeries <- dataSeries + summedWeighted
   return(fracDiffSeries) } 
#  
#####################################################################################################


#genFracWeightedSeries(dataSeries = hpiData$HPI,d = .75,threshold = 1e-5,size = 20)





#################################################################################################### 
# Function Name: identifyDifferencing 
# Description: 
# Inputs: Generate a list of potential d values, creates the weights, and then generates a set of
#         fractionally difference data series. Then, runs the augmented Dickey-Fuller test on each
#         of them to see the outcome. The statistics from the ADF testis then compared and output
#         as either a recommendation (if mode is "suggestion") or as a graph ("chart")
# [1] dataSeries - the data series to test on.
# [2] dLow - Numeric giving the lowest value for d for testing. Defaults to 0
# [3] dHigh - Numeric giving the highest value for d for testing.  Defaults to 1
# [4] steps - Numeric giving the numbers of steps between dLow and dHigh to use. Defaults to 10
# [5] size - The number of results to generate from the fracWeights function. Defaults to 10.
# Outputs:
# [1] dSuggestion - a list object including a suggested d value (based on a 5% confidence interval
# for stationarity) and a plot showing the values based on the ADF test.
#  
identifyDifferencing <- function( dataSeries, dLow, dHigh,size = 20,steps = 20,threshold = 1e-5, pThreshold = .1) { 
   dStep = (dHigh-dLow)/(steps )
   dLow <- ifelse(dLow ==0,  dStep,dLow)
   dRange <- seq(dLow,dHigh,dStep)
   # Generate a list of transformed data series as a list.
   diffSeries <- lapply( X = dRange , function(x){ genFracWeightedSeries(dataSeries ,d = x,threshold = 1e-5,size = 20)}  ) 
   # Run the adf test on each transformed series
   adfResults <- sapply(X = 1:length(diffSeries),FUN = function(x){adf.test(x = na.remove(diffSeries[[x]]),k = 5)$p.value})
#   adfResults <- sapply(X = 1:length(diffSeries),FUN = function(x){kpss.test(x = na.remove(diffSeries[[x]]) )$p.value})
   frameForIndexing <- as.data.table(list("d" = dRange,"ADF P-value" = adfResults))
   # Select the d value suggestion based on adf value; Return if model = "suggestion"
   suggestedD <- frameForIndexing[`ADF P-value` < pThreshold,min(d)]
   # Generate the plot if that method is selected; Return chart if model="plot"
   dSeries <- ggplot(frameForIndexing) + 
     geom_point(aes(x = d,y = `ADF P-value`)) + theme_bw()+theme(axis.text = element_text(size = 13),
                                                               legend.position = "bottom",
                                                               axis.title = element_text(size = 16 ),
                                                               text = element_text(family = "sans"), 
                                                               title = element_text(size = 20),
                                                               legend.text = element_text(size = 13),
                                                               legend.title = element_blank()) + 
                                                               geom_hline(yintercept = pThreshold) + 
                                                          ggtitle("ADF Results by p-value")
   dSuggestion <- list( "d" = suggestedD ,"Plot" = dSeries   )
   return(dSuggestion) 
} 
#  
#####################################################################################################


  